### ISSUE TITLE
File Input Issue - multiple fields

### ISSUE THREAD

**Issue by thrilliant** [PaystackHQ/Wordpress-Payment-forms-for-Paystack#10]
There is an error when a form has multiple input fields. The uploads are detected and submitted but the user only gets a successful visual feedback for one of the input fields. 

E.g file-path is shown on the first input field and the second input field gives a no file selected error.

This, however, doesn't break the form or stop both files from being submitted and uploaded into the WordPress media gallery.

**Comment by cyakpofure** [comment]
Hello,

I also have this same problem. Please see link here http://fohiglobal.com/chapter-registration/

This is confusing to people and putting them off from paying.
